// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeMode(arg1:string):Promise<void>;

export function StartStream(arg1:string,arg2:string):Promise<string>;

export function StopStream():Promise<void>;

export function TogglePiP():Promise<void>;
